# Generated by Django 5.0.6 on 2026-08-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesoreriacontraparte',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tesoreriacontraparte',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('fisica', 'Fisica'), ('moral', 'Moral'), ('fisica_act_emp', 'Fisica con actividad empresarial'), ('fideicomiso', 'Fideicomiso')], max_length=20, null=True),
        ),
    ]
