# Generated by Django 5.0.6 on 2026-08-24 20:53

from django.db import migrations, models


# Backfill (24/Ago/2026): facturas capturadas antes de este cambio pueden
# tener estado=NULL/"" o texto libre que ya no es uno de los 4 estados
# formales (ej. "vigente"/"cancelada" del CFDI, que antes vivian aqui mismo
# sin choices). No se pisan valores que ya coinciden con un estado valido -
# solo se normaliza lo que quedaria vacio o fuera del catalogo nuevo, para
# que el frontend siempre tenga un Chip que mostrar.
def normaliza_estados_existentes(apps, schema_editor):
    TesoreriaFactura = apps.get_model("tesoreria", "TesoreriaFactura")
    estados_validos = {"PENDIENTE", "EN_PROCESO", "ACEPTADA", "RECHAZADA"}
    TesoreriaFactura.objects.exclude(estado__in=estados_validos).update(estado="PENDIENTE")


def sin_reversa(apps, schema_editor):
    # No hay forma de recuperar el valor de texto libre original una vez
    # normalizado - la reversa de esta migracion solo deshace el esquema
    # (columna/choices), no los datos.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_alter_tesoreriacontraparte_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriafactura',
            name='link_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tesoreriafactura',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=50, null=True),
        ),
        migrations.RunPython(normaliza_estados_existentes, sin_reversa),
    ]
