# Generated by Django 5.0.6 on 2026-08-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0007_seed_nota_credito_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriacomplementopago',
            name='contraparte',
            field=models.ForeignKey(blank=True, db_column='id_contraparte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complementos_pago', to='tesoreria.tesoreriacontraparte'),
        ),
        migrations.AddField(
            model_name='tesoreriafactura',
            name='contraparte',
            field=models.ForeignKey(blank=True, db_column='id_contraparte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='tesoreria.tesoreriacontraparte'),
        ),
        migrations.AddField(
            model_name='tesorerianotacredito',
            name='contraparte',
            field=models.ForeignKey(blank=True, db_column='id_contraparte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_emitidas', to='tesoreria.tesoreriacontraparte'),
        ),
    ]
