# Generated by Django 5.0.6 on 2026-08-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0009_backfill_contraparte_por_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriacuenta',
            name='sociedad',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriacuenta',
            name='tipo',
            field=models.CharField(choices=[('CHEQUES', 'Cheques'), ('INVERSION', 'Inversión'), ('NOMINA', 'Nómina'), ('OTRA', 'Otra')], default='CHEQUES', max_length=20),
        ),
    ]
