# Generated by Django 5.0.6 on 2026-08-27 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0013_tesoreriaticketreembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriaticketreembolso',
            name='factura',
            field=models.ForeignKey(blank=True, db_column='factura_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_reembolso', to='tesoreria.tesoreriafactura', to_field='timbre_uuid'),
        ),
        migrations.AlterField(
            model_name='tesoreriaticketreembolso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado — pendiente de facturar'), ('VINCULADO', 'Facturado y vinculado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
