# Generated by Django 5.0.6 on 2026-08-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0015_tesoreriaticketproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesoreriaContratoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('obligatorio', models.BooleanField(default=True)),
                ('recibido', models.BooleanField(default=False)),
                ('link_archivo', models.TextField(blank=True, null=True)),
                ('drive_file_id', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='tesoreria.tesoreriacontrato')),
            ],
            options={
                'db_table': 'tesoreria_contrato_documentos',
                'ordering': ['contrato', 'id'],
            },
        ),
    ]
