# Generated by Django 5.0.6 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0016_tesoreriacontratodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesoreriacontratodocumento',
            name='nombre',
            field=models.CharField(
                choices=[
                    ('CONTRATO_FIRMADO', 'Contrato firmado (PDF)'),
                    ('IDENTIFICACION_OFICIAL', 'Identificación oficial del representante legal'),
                    ('COMPROBANTE_DOMICILIO', 'Comprobante de domicilio'),
                    ('CONSTANCIA_SITUACION_FISCAL', 'Constancia de situación fiscal (RFC)'),
                    ('ACTA_CONSTITUTIVA', 'Acta constitutiva'),
                    ('PODER_NOTARIAL', 'Poder notarial del representante legal'),
                    ('POLIZA_SEGURO', 'Póliza de seguro'),
                    ('REFERENCIAS_BANCARIAS', 'Referencias bancarias'),
                    ('OTRO', 'Otro (especificar en comentarios)'),
                ],
                max_length=50,
            ),
        ),
    ]
