# Generated by Django 5.0.6 on 2026-08-28

import django.db.models.deletion
import tesoreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0017_contrato_documento_nombre_catalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesoreriaDocumentoTicket',
            fields=[
                ('id_ticket', models.CharField(default=tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.CharField(blank=True, max_length=8, null=True)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.IntegerField(default=1)),
                ('uses_count', models.IntegerField(default=0)),
                ('first_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tesoreria.tesoreriacontratodocumento')),
            ],
            options={
                'db_table': 'tesoreria_documento_tickets',
                'ordering': ['-issued_at'],
            },
        ),
    ]
