# Generated by Django 5.0.6 on 2026-08-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0020_contraparte_origen_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriaticketreembolso',
            name='categoria_gasto',
            field=models.CharField(blank=True, choices=[('VIATICOS', 'Viáticos'), ('PAPELERIA', 'Papelería'), ('TRANSPORTE', 'Transporte'), ('ALIMENTOS', 'Alimentos'), ('HOSPEDAJE', 'Hospedaje'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriaticketreembolso',
            name='centro',
            field=models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('OBRA', 'Obra'), ('VENTAS', 'Ventas'), ('TESORERIA', 'Tesorería'), ('RRHH', 'RRHH'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriaticketreembolso',
            name='moneda',
            field=models.CharField(choices=[('MXP', 'MXP'), ('USD', 'USD'), ('EUR', 'EUR')], default='MXP', max_length=5),
        ),
        migrations.AddField(
            model_name='tesoreriaticketreembolso',
            name='sociedad',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
