# Generated by Django 5.0.6 on 2026-08-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0021_tesoreriaticketreembolso_categoria_gasto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriaticketproveedor',
            name='proyecto',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriaticketproveedor',
            name='sociedad',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
