# Generated by Django 5.0.6 on 2026-09-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0022_tesoreriaticketproveedor_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesoreriacontraparte',
            name='origen',
            field=models.CharField(choices=[('manual', 'Alta manual'), ('ia', 'Alta automatica por IA'), ('pld', 'Alta automatica desde PLD (expediente autónomo)')], default='manual', max_length=10),
        ),
    ]
