# Generated by Django 5.0.6 on 2026-09-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0023_alter_tesoreriacontraparte_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriacontraparte',
            name='fusionado_en',
            field=models.ForeignKey(blank=True, db_column='fusionado_en', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_fusionados', to='tesoreria.tesoreriacontraparte'),
        ),
    ]
