# Generated by Django 5.0.6 on 2026-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0025_alter_tesoreriacontraparte_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesoreriacontraparte',
            name='genero',
            field=models.CharField(blank=True, choices=[('MUJER', 'Mujer'), ('HOMBRE', 'Hombre'), ('X', 'No binario')], max_length=20, null=True),
        ),
    ]
