# Generated by Django 5.0.6 on 2026-09-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0026_alter_tesoreriacontraparte_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesoreriacontraparte',
            name='origen',
            field=models.CharField(choices=[('manual', 'Alta manual'), ('ia', 'Alta automatica por IA'), ('pld', 'Alta automatica desde PLD (expediente autónomo)'), ('selector', 'Alta mínima desde selector (pendiente completar por ticket)')], default='manual', max_length=10),
        ),
    ]
