# Generated by Django 5.0.6 on 2026-09-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0027_alter_tesoreriacontraparte_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesoreriaDiaFestivo',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tesoreria_dias_festivos',
                'ordering': ['fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='tesoreriaticketreembolso',
            name='centro',
        ),
        migrations.AddField(
            model_name='tesoreriaticketreembolso',
            name='autorizado_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriaticketreembolso',
            name='fecha_autorizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
