# Generated by Django 5.0.6 on 2026-09-03 22:51

import django.db.models.deletion
import tesoreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0028_tesoreriadiafestivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesoreriaticketreembolso',
            name='categoria_gasto',
        ),
        migrations.RemoveField(
            model_name='tesoreriaticketreembolso',
            name='monto',
        ),
        migrations.AlterField(
            model_name='tesoreriaticketreembolso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TesoreriaTicketReembolsoConcepto',
            fields=[
                ('id_concepto', models.CharField(default=tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('categoria_gasto', models.CharField(blank=True, choices=[('VIATICOS', 'Viáticos'), ('PAPELERIA', 'Papelería'), ('TRANSPORTE', 'Transporte'), ('ALIMENTOS', 'Alimentos'), ('HOSPEDAJE', 'Hospedaje'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('ticket', models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='tesoreria.tesoreriaticketreembolso')),
            ],
            options={
                'db_table': 'tesoreria_tickets_reembolso_conceptos',
            },
        ),
    ]
