# Generated by Django 5.0.6 on 2026-09-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0029_remove_tesoreriaticketreembolso_categoria_gasto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesoreriaSolicitudPago',
            fields=[
                ('id_solicitud', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=8)),
                ('sociedad', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo', models.CharField(choices=[('SERVICIO', 'Servicio'), ('LICENCIA', 'Licencia'), ('RENOVACION', 'Renovación'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(choices=[('MXP', 'MXP'), ('USD', 'USD'), ('EUR', 'EUR')], default='MXP', max_length=5)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado — pendiente de pago'), ('RECHAZADO', 'Rechazado'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('solicitado_por', models.CharField(max_length=255)),
                ('autorizado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
                ('link_comprobante', models.TextField(blank=True, null=True)),
                ('drive_file_id_comprobante', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('factura', models.ForeignKey(blank=True, db_column='factura_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_pago', to='tesoreria.tesoreriafactura', to_field='timbre_uuid')),
                ('flujo', models.ForeignKey(blank=True, db_column='id_flujo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_pago', to='tesoreria.tesoreriaflujo')),
            ],
            options={
                'db_table': 'tesoreria_solicitudes_pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
