# Generated by Django 5.0.6 on 2026-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0030_tesoreriasolicitudpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriaticketreembolso',
            name='mime_type_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriaticketreembolso',
            name='mime_type_ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
