# Generated by Django 5.0.6 on 2026-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0031_tesoreriaticketreembolso_mime_type_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriasolicitudpago',
            name='mime_type_comprobante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
