# Generated by Django 5.0.6 on 2026-09-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0032_tesoreriasolicitudpago_mime_type_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriacontrato',
            name='categoria',
            field=models.CharField(blank=True, choices=[('FORMAL_RECURRENTE', 'Formal / recurrente'), ('GASTO_SUELTO', 'Gasto suelto / consumo único'), ('REEMBOLSO_EMPLEADO', 'Reembolso de empleado'), ('COMPRA_ADQUISICION', 'Compra / adquisición')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tesoreriaticketreembolsoconcepto',
            name='categoria_gasto',
            field=models.CharField(blank=True, choices=[('VIATICOS', 'Viáticos'), ('PAPELERIA', 'Papelería'), ('TRANSPORTE', 'Transporte'), ('ALIMENTOS', 'Alimentos'), ('HOSPEDAJE', 'Hospedaje'), ('ADMINISTRACION', 'Administración'), ('RECURSOSHUMANOS', 'Recursos Humanos'), ('LEGAL', 'Legal'), ('EXTRAORDINARIOS', 'Extraordinarios')], max_length=20, null=True),
        ),
    ]
