# Generated by Django 5.0.6 on 2026-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0033_contrato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriafactura',
            name='drive_file_id_pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriafactura',
            name='drive_file_id_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriafactura',
            name='mime_type_pdf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriafactura',
            name='mime_type_xml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
