# Generated by Django 5.0.6 on 2026-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0034_factura_drive_file_id_pdf_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriacontraparte',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
