# Generated by Django 5.0.6 on 2026-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0035_tesoreriacontraparte_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesoreriacontraparte',
            name='sucursal',
        ),
    ]
