# Generated by Django 5.0.6 on 2026-09-08 19:56

import django.db.models.deletion
import tesoreria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0036_remove_tesoreriacontraparte_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesoreriaMovimientoBancario',
            fields=[
                ('id', models.CharField(default=tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('abono', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('corte_edc', models.ForeignKey(blank=True, db_column='corte_edc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='tesoreria.tesoreriacorteedc')),
                ('cuenta', models.ForeignKey(db_column='cuenta', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_bancarios', to='tesoreria.tesoreriacuenta')),
                ('flujo', models.ForeignKey(blank=True, db_column='flujo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='tesoreria.tesoreriaflujo')),
            ],
            options={
                'db_table': 'tesoreria_movimientos_bancarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
