# Generated by Django 5.0.6 on 2026-09-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0037_tesoreriamovimientobancario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriacorteedc',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriacorteedc',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
