# Generated by Django 5.0.6 on 2026-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0038_tesoreriacorteedc_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriafactura',
            name='categoria_gasto',
            field=models.CharField(blank=True, choices=[('VIATICOS', 'Viáticos'), ('PAPELERIA', 'Papelería'), ('TRANSPORTE', 'Transporte'), ('ALIMENTOS', 'Alimentos'), ('HOSPEDAJE', 'Hospedaje'), ('ADMINISTRACION', 'Administración'), ('RECURSOSHUMANOS', 'Recursos Humanos'), ('LEGAL', 'Legal'), ('EXTRAORDINARIOS', 'Extraordinarios')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriaflujo',
            name='categoria_gasto',
            field=models.CharField(blank=True, choices=[('VIATICOS', 'Viáticos'), ('PAPELERIA', 'Papelería'), ('TRANSPORTE', 'Transporte'), ('ALIMENTOS', 'Alimentos'), ('HOSPEDAJE', 'Hospedaje'), ('ADMINISTRACION', 'Administración'), ('RECURSOSHUMANOS', 'Recursos Humanos'), ('LEGAL', 'Legal'), ('EXTRAORDINARIOS', 'Extraordinarios')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriasolicitudpago',
            name='categoria_gasto',
            field=models.CharField(blank=True, choices=[('VIATICOS', 'Viáticos'), ('PAPELERIA', 'Papelería'), ('TRANSPORTE', 'Transporte'), ('ALIMENTOS', 'Alimentos'), ('HOSPEDAJE', 'Hospedaje'), ('ADMINISTRACION', 'Administración'), ('RECURSOSHUMANOS', 'Recursos Humanos'), ('LEGAL', 'Legal'), ('EXTRAORDINARIOS', 'Extraordinarios')], max_length=20, null=True),
        ),
    ]
