# Generated by Django 5.0.6 on 2026-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0039_tesoreriafactura_categoria_gasto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriaticketproveedor',
            name='drive_file_id_pdf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriaticketproveedor',
            name='mime_type_pdf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
