# Generated by Django 5.0.6 on 2026-09-09 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0040_tesoreriaticketproveedor_drive_file_id_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriafactura',
            name='ticket_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='tesoreria.tesoreriaticketproveedor'),
        ),
    ]
