# Generated by Django 5.0.6 on 2026-09-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0041_tesoreriafactura_ticket_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriaticketproveedor',
            name='drive_file_id_xml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriaticketproveedor',
            name='mime_type_xml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
