# Generated by Django 5.0.6 on 2026-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0042_tesoreriaticketproveedor_drive_file_id_xml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriafactura',
            name='comprobante_iva',
            field=models.DecimalField(blank=True, db_column='Comprobante_IVA', decimal_places=2, max_digits=18, null=True),
        ),
    ]
