# Generated by Django 5.0.6 on 2026-09-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0042_tesoreriaticketproveedor_drive_file_id_xml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriaflujo',
            name='iva_mxp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
