# Generated by Django 5.0.6 on 2026-09-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0043_tesoreriafactura_comprobante_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriacomplementopago',
            name='drive_file_id_pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriacomplementopago',
            name='drive_file_id_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriacomplementopago',
            name='link_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriacomplementopago',
            name='mime_type_pdf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriacomplementopago',
            name='mime_type_xml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tesorerianotacredito',
            name='drive_file_id_pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesorerianotacredito',
            name='drive_file_id_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesorerianotacredito',
            name='link_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesorerianotacredito',
            name='mime_type_pdf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tesorerianotacredito',
            name='mime_type_xml',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
