# Generated by Django 5.0.6 on 2026-09-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0043_tesoreriaflujo_iva_mxp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriaflujo',
            name='requiere_cfdi',
            field=models.BooleanField(default=True),
        ),
    ]
