# Generated by Django 5.0.6 on 2026-09-10 19:03
# 10/Sep/2026: encontrado en el seed demo1eb1 (0005_seed_flujo_demo) - un
# flujo con pagado=True pero validacion_estado="PENDIENTE", inconsistente
# con el flujo real de la app (aprobar() siempre pone autorizacion=True Y
# validacion_estado=APROBADA juntos, ver TesoreriaFlujoViewSet.aprobar).
# Corrige los datos existentes antes de agregar la constraint, para no
# tumbar instalaciones con filas viejas asi.

from django.db import migrations, models


def fix_pagados_sin_aprobada(apps, schema_editor):
    TesoreriaFlujo = apps.get_model("tesoreria", "TesoreriaFlujo")
    TesoreriaFlujo.objects.filter(pagado=True).exclude(validacion_estado="APROBADA").update(
        validacion_estado="APROBADA", aprobacion_lista=True
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0044_tesoreriacomplementopago_drive_file_id_pdf_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_pagados_sin_aprobada, noop),
        migrations.AddConstraint(
            model_name='tesoreriaflujo',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('pagado', True), _negated=True), ('validacion_estado', 'APROBADA'), _connector='OR'), name='tesoreria_flujo_pagado_requiere_aprobada'),
        ),
    ]
