# Generated by Django 5.0.6 on 2026-09-10 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0045_fix_validacion_estado_flujos_pagados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesoreriaNomina',
            fields=[
                ('id_nomina', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('QUINCENAL', 'Quincenal (corporativo)'), ('SEMANAL', 'Semanal (obra)')], max_length=20)),
                ('sociedad', models.CharField(max_length=13)),
                ('proyecto', models.CharField(blank=True, max_length=3, null=True)),
                ('centro', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVO', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tesoreria_nominas',
            },
        ),
        migrations.AddField(
            model_name='tesoreriaflujo',
            name='periodo_nomina',
            field=models.ForeignKey(blank=True, db_column='id_nomina_periodo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flujos', to='tesoreria.tesorerianomina'),
        ),
    ]
