# Generated by Django 5.0.6 on 2026-09-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0046_tesoreria_nomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesorerianomina',
            name='proyecto',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
