# Generated by Django 5.0.6 on 2026-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0047_tesoreria_nomina_proyecto_liga_vivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriarecnomina',
            name='drive_file_id_comprobante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriarecnomina',
            name='link_comprobante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tesoreriarecnomina',
            name='mime_type_comprobante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
