# Generated by Django 5.0.6 on 2026-09-14 15:47 (editado a mano: se agrega
# el paso de datos que copia el `sociedad` unico de cada Nomina existente
# a la tabla nueva ANTES de borrar la columna vieja - 14/Sep/2026, "porque
# no se puede poner dos sociedades, ya que pueden estar contratados por dos
# sociedades").

import django.db.models.deletion
from django.db import migrations, models


def copiar_sociedad_existente(apps, schema_editor):
    TesoreriaNomina = apps.get_model("tesoreria", "TesoreriaNomina")
    TesoreriaNominaSociedad = apps.get_model("tesoreria", "TesoreriaNominaSociedad")
    for nomina in TesoreriaNomina.objects.all():
        if nomina.sociedad:
            TesoreriaNominaSociedad.objects.get_or_create(nomina=nomina, sociedad=nomina.sociedad)


def revertir_a_sociedad_unica(apps, schema_editor):
    TesoreriaNomina = apps.get_model("tesoreria", "TesoreriaNomina")
    TesoreriaNominaSociedad = apps.get_model("tesoreria", "TesoreriaNominaSociedad")
    for nomina in TesoreriaNomina.objects.all():
        primera = TesoreriaNominaSociedad.objects.filter(nomina=nomina).order_by("id").first()
        if primera:
            nomina.sociedad = primera.sociedad
            nomina.save(update_fields=["sociedad"])


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0048_tesoreriarecnomina_drive_file_id_comprobante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesoreriaNominaSociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociedad', models.CharField(max_length=13)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociedades', to='tesoreria.tesorerianomina')),
            ],
            options={
                'db_table': 'tesoreria_nominas_sociedades',
            },
        ),
        migrations.RunPython(copiar_sociedad_existente, revertir_a_sociedad_unica),
        migrations.RemoveField(
            model_name='tesorerianomina',
            name='sociedad',
        ),
        migrations.AddConstraint(
            model_name='tesorerianominasociedad',
            constraint=models.UniqueConstraint(fields=('nomina', 'sociedad'), name='unique_nomina_sociedad'),
        ),
    ]
