# Generated by Django 5.0.6 on 2026-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0049_remove_tesorerianomina_sociedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesoreriafactura',
            name='comprobante_metodo_pago',
            field=models.CharField(blank=True, choices=[('PUE', 'Pago en una sola exhibición'), ('PPD', 'Pago en parcialidades o diferido')], db_column='Comprobante_MetodoPago', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tesorerianotacredito',
            name='comprobante_metodo_pago',
            field=models.CharField(blank=True, choices=[('PUE', 'Pago en una sola exhibición'), ('PPD', 'Pago en parcialidades o diferido')], db_column='Comprobante_MetodoPago', max_length=5, null=True),
        ),
    ]
