# Generated by Django 5.0.6 on 2026-09-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0051_borra_datos_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriaflujo',
            name='drive_file_id_referencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
