# Generated by Django 5.0.6 on 2026-09-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0052_tesoreriaflujo_drive_file_id_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesoreriacontrato',
            name='sociedad',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
