# Generated by Django 5.0.6 on 2026-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0057_seed_proyecto_codigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesoreriacuenta',
            name='tipo',
            field=models.CharField(choices=[('CHEQUES', 'Cheques'), ('INVERSION', 'Inversión'), ('NOMINA', 'Nómina'), ('PAGARE', 'Pagaré'), ('FIDEICOMISO', 'Fideicomiso'), ('OTRA', 'Otra')], default='CHEQUES', max_length=20),
        ),
    ]
