# Generated by Django 5.0.6 on 2026-09-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0058_alter_tesoreriacuenta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesoreriacuenta',
            name='disponible_ministrar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='tesoreriacuenta',
            name='tipo',
            field=models.CharField(choices=[('CHEQUES', 'Cheques'), ('INVERSION', 'Inversión'), ('NOMINA', 'Nómina'), ('PAGARE', 'Pagaré'), ('FIDEICOMISO', 'Fideicomiso'), ('CREDITO', 'Crédito'), ('OTRA', 'Otra')], default='CHEQUES', max_length=20),
        ),
    ]
