# Generated by Django 5.0.6 on 2026-09-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0059_tesoreriacuenta_disponible_ministrar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesoreriacuenta',
            name='disponible_ministrar',
        ),
        migrations.AddField(
            model_name='tesoreriasaldo',
            name='disponible_ministrar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
