# Generated by Django 5.0.6 on 2026-10-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0061_contrato_concepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesoreriaflujo',
            name='fecha_pago_original',
        ),
    ]
