# Generated by Django 5.0.6 on 2026-07-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequestlog',
            name='proveedor_usado',
            field=models.CharField(default='ai-studio', help_text="'ai-studio' (documentos ficticios) o 'vertex-ai' (documentos reales).", max_length=20),
        ),
        migrations.AlterField(
            model_name='analysisrequestlog',
            name='servicio_solicitante',
            field=models.CharField(help_text="Ej. 'pld-service'", max_length=50),
        ),
    ]
