# Generated by Django 5.0.6 on 2026-08-13 18:20

import docint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docint', '0002_alter_analysisrequestlog_proveedor_usado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.CharField(default=docint.models._request_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=12)),
                ('gcs_uri', models.CharField(help_text='URI de staging (docint/storage.py), no el archivo final.', max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('expected_document_type', models.CharField(blank=True, max_length=100)),
                ('internal_prompt_key', models.CharField(max_length=100)),
                ('matched_by_filename', models.BooleanField(default=None, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('servicio_solicitante', models.CharField(default='desconocido', max_length=50)),
                ('resultado', models.JSONField(blank=True, help_text='DocumentAnalysisResult serializado, solo si COMPLETADO.', null=True)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('max_intentos', models.PositiveIntegerField(default=3)),
                ('cloud_task_name', models.CharField(blank=True, default='', max_length=200)),
                ('solicitado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'docint_analysis_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
