# Generated by Django 5.0.6 on 2026-08-10 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_seed_sociedades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalgrupo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='iam.iamuser'),
        ),
        migrations.AlterField(
            model_name='generalsociedad',
            name='grupo',
            field=models.CharField(blank=True, help_text='Columna real del ERD. Nivel GRUPO como scope_type formal sigue sin decidir por el cliente (roles-y-permisos.md sec. 5, punto 1); general_grupos/iam_groups de abajo son la via explicita pedida para este arranque, no reemplazan esa decision pendiente.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iamgroup',
            name='alias',
            field=models.CharField(blank=True, help_text="Nombre corto para mostrar en pantalla (ej. 'CUMBRES' para 'CONSULTORÍA Y PROYECTOS CUMBRES').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iamgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='iam.iamuser'),
        ),
        migrations.AlterField(
            model_name='iamgroup',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Holding empresarial al que pertenece este equipo, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='iam.generalgrupo'),
        ),
        migrations.AlterField(
            model_name='iamusergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to='iam.iamuser'),
        ),
        migrations.CreateModel(
            name='IamUserCentroAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('centro_id', models.CharField(max_length=255)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centro_access_granted', to='iam.iamuser')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='centro_access', to='iam.iamuser')),
            ],
            options={
                'db_table': 'iam_user_centro_access',
            },
        ),
        migrations.CreateModel(
            name='IamUserContratoAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_contrato', models.CharField(max_length=255)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_access_granted', to='iam.iamuser')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contrato_access', to='iam.iamuser')),
            ],
            options={
                'db_table': 'iam_user_contrato_access',
            },
        ),
    ]
