# Generated by Django 5.0.6 on 2026-08-10 22:27
#
# Limpieza de "grupo" en el codigo (decision 10/Ago/2026, ver memoria de
# sesion): GeneralGrupo (holding) era redundante con IamGroup y nunca se
# reconcilio con el cliente (marcado "sin decidir" en
# roles-y-permisos.md) - se elimina. IamGroup/IamUserGroup se quedan tal
# cual: NO son el nivel de alcance GRUPO ya descartado, son el catalogo
# real de "empresa del usuario" que usa el directorio.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_centro_contrato_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iamgroup',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='GeneralGrupo',
        ),
    ]
