# Generated by Django 5.0.6 on 2026-08-10 22:56

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0008_eliminar_general_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamInvitation',
            fields=[
                ('invitation_id', models.CharField(default=iam.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to='iam.iamuser')),
            ],
            options={
                'db_table': 'iam_invitations',
            },
        ),
    ]
