# Generated by Django 5.0.6 on 2026-08-14 16:25

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0009_agrega_iam_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamExternalCollaborator',
            fields=[
                ('external_access_id', models.CharField(default=iam.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_access_issued', to='iam.iamuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_access', to='iam.iamuser')),
            ],
            options={
                'db_table': 'iam_external_collaborators',
            },
        ),
    ]
