# Generated by Django 5.0.6 on 2026-08-17 23:05
#
# Merge de dos migraciones 0010 independientes (17/Ago/2026, CI /
# iam-service fallando con "Conflicting migrations detected"):
# 0010_iamexternalcollaborator (rama del 3er tipo de invitacion, 14/Ago) y
# 0010_seed_docint_analizar (rama del Motor Documental, 13-17/Ago) se
# desarrollaron en paralelo sobre la misma base (0009) y ninguna dependia de
# la otra - dos leaf nodes en el grafo de migraciones. No hay cambio de
# esquema/datos propio, solo declara el orden.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0010_iamexternalcollaborator'),
        ('iam', '0010_seed_docint_analizar'),
    ]

    operations = [
    ]
