# Generated by Django 5.0.6 on 2026-08-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0014_merge_seed_docint_tesoreria_pld_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamrole',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
