# Generated by Django 5.0.6 on 2026-08-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0015_iamrole_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamrole',
            name='tipo',
            field=models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], default='INTERNO', max_length=10),
        ),
    ]
