# Generated by Django 5.0.6 on 2026-09-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0017_seed_solicitud_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamGooglePersonalToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='google_personal_token', serialize=False, to='iam.iamuser')),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iam_google_personal_tokens',
            },
        ),
    ]
