# Generated by Django 5.0.6 on 2026-10-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0020_gmail_send_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamgmailsendtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gmail_send_token', serialize=False, to='iam.iamuser'),
        ),
        migrations.AlterUniqueTogether(
            name='iamusergroup',
            unique_together={('user', 'group', 'alcance_tipo', 'alcance_id')},
        ),
    ]
