# Generated by Django 5.0.6 on 2026-09-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viviendaventasexpediente',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('INFONAVIT', 'Infonavit'), ('FOVISSSTE', 'Fovissste'), ('COFINAVIT', 'Cofinavit'), ('HIPOTECARIO', 'Hipotecario')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='viviendaventasexpediente',
            name='pagos_efectivo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viviendaventasexpedienteitem',
            name='responsable',
            field=models.CharField(blank=True, choices=[('VENTAS', 'Ventas'), ('ESCRITURACION', 'Escrituración'), ('TESORERIA', 'Tesorería'), ('CONTABILIDAD', 'Contabilidad'), ('LEGAL', 'Legal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='viviendaventasexpediente',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN PROCESO', 'En proceso'), ('FIRMADO', 'Firmado'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='viviendaventasexpedienteitem',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NO APLICA', 'No aplica'), ('INCOMPLETO', 'Incompleto'), ('ENTREGADO', 'Entregado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('POSPUESTO', 'Pospuesto')], default='PENDIENTE', max_length=20),
        ),
    ]
