# Generated by Django 5.0.6 on 2026-08-21 15:50

import django.db.models.deletion
import obra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraCorteSemanal',
            fields=[
                ('id_corte', models.CharField(default=obra.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=3)),
                ('fecha_corte', models.DateField()),
                ('semana_de_fase', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20)),
                ('aprobado_por', models.CharField(blank=True, max_length=8, null=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'obra_cortes_semanales',
                'ordering': ['-fecha_corte'],
            },
        ),
        migrations.CreateModel(
            name='ObraEtapa',
            fields=[
                ('id_etapa', models.CharField(default=obra.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('numero', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'obra_etapas',
                'ordering': ['orden', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ObraLote',
            fields=[
                ('id_lote', models.CharField(default=obra.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=3)),
                ('obra', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('manzana', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_lote', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'obra_lotes',
                'ordering': ['proyecto', 'manzana', 'numero_lote'],
            },
        ),
        migrations.CreateModel(
            name='ObraConcepto',
            fields=[
                ('id_concepto', models.CharField(default=obra.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('maestro', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=8, null=True)),
                ('etapa', models.ForeignKey(db_column='id_etapa', on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='obra.obraetapa')),
            ],
            options={
                'db_table': 'obra_conceptos',
                'ordering': ['etapa', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ObraEstimacion',
            fields=[
                ('id_estimacion', models.CharField(default=obra.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('numero_estimacion', models.PositiveSmallIntegerField()),
                ('porcentaje', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fecha_captura', models.DateField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=8, null=True)),
                ('concepto', models.ForeignKey(db_column='id_concepto', on_delete=django.db.models.deletion.PROTECT, related_name='estimaciones', to='obra.obraconcepto')),
                ('lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.PROTECT, related_name='estimaciones', to='obra.obralote')),
            ],
            options={
                'db_table': 'obra_estimaciones',
                'ordering': ['concepto', 'lote', 'numero_estimacion'],
            },
        ),
    ]
