# Generated by Django 5.0.6 on 2026-08-21 16:33

import django.db.models.deletion
import obra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraEvidencia',
            fields=[
                ('id_evidencia', models.CharField(default=obra.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('link_drive', models.CharField(blank=True, max_length=2083, null=True)),
                ('fecha_captura', models.DateField()),
                ('revisado', models.BooleanField(default=False)),
                ('revisado_por', models.CharField(blank=True, max_length=8, null=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=8, null=True)),
                ('concepto', models.ForeignKey(db_column='id_concepto', on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='obra.obraconcepto')),
                ('lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='obra.obralote')),
            ],
            options={
                'db_table': 'obra_evidencias',
                'ordering': ['-fecha_captura'],
            },
        ),
    ]
