# Generated by Django 5.0.6 on 2026-08-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0002_obraevidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraconcepto',
            name='es_personal_eventual',
            field=models.BooleanField(default=False),
        ),
    ]
