# Generated by Django 5.0.6 on 2026-08-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0003_obraconcepto_es_personal_eventual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obraconcepto',
            name='es_personal_eventual',
        ),
    ]
