# Generated by Django 5.0.6 on 2026-08-21 19:35

import django.db.models.deletion
import obra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0004_remove_obraconcepto_es_personal_eventual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraCorteSemanalDetalle',
            fields=[
                ('id_detalle', models.CharField(default=obra.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('porcentaje_acumulado', models.DecimalField(decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(db_column='id_concepto', on_delete=django.db.models.deletion.PROTECT, to='obra.obraconcepto')),
                ('corte', models.ForeignKey(db_column='id_corte', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='obra.obracortesemanal')),
                ('lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.PROTECT, to='obra.obralote')),
            ],
            options={
                'db_table': 'obra_cortes_semanales_detalle',
                'ordering': ['concepto', 'lote'],
                'unique_together': {('corte', 'concepto', 'lote')},
            },
        ),
    ]
