# Generated by Django 5.0.6 on 2026-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0005_obracortesemanaldetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='obralote',
            name='identificador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obralote',
            name='tipo',
            field=models.CharField(choices=[('CASA', 'Casa'), ('ESPECIAL', 'Especial')], default='CASA', max_length=10),
        ),
        migrations.AlterField(
            model_name='obralote',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
