# Generated by Django 5.0.6 on 2026-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0006_obralote_identificador_obralote_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obracortesemanal',
            name='proyecto',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='obralote',
            name='proyecto',
            field=models.CharField(max_length=8),
        ),
    ]
