# Generated by Django 5.0.6 on 2026-08-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0003_sociedad_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartedoc',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartedoc',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartedoc',
            name='subido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartedoc',
            name='tamano_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
