# Generated by Django 5.0.6 on 2026-08-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0004_pldcontrapartedoc_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='estado_llenado_manual',
            field=models.BooleanField(default=False),
        ),
    ]
