# Generated by Django 5.0.6 on 2026-08-17 19:05

import pld.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0005_pldcontrapartekyc_estado_llenado_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='dom_calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='dom_colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='dom_cp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='dom_estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='dom_municipio_alcaldia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='dom_numero_ext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='dom_numero_int',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='dom_pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='fecha_nac_const',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='id_contraparte',
            field=models.CharField(default=pld.models._short_id, max_length=8),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='ident_fideicomiso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='ocupacion_act_economica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='pais_nac_const',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='telefono_sms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
