# Generated by Django 5.0.6 on 2026-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0006_alter_pldcontrapartekyc_dom_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='estado_cuenta',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('SOSPECHOSA', 'Marcada como sospechosa'), ('CONGELADA', 'Congelada')], default='ACTIVA', max_length=20),
        ),
    ]
