# Generated by Django 5.0.6 on 2026-08-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0007_pldcontrapartekyc_estado_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
