# Generated by Django 5.0.6 on 2026-08-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0008_pldcontrapartekyc_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='consentimiento_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='politicas_aceptadas_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='veracidad_declarada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
