# Generated by Django 5.0.6 on 2026-08-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0009_consentimiento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)'), ('UNION_LIBRE', 'Unión libre / Concubinato')], max_length=20, null=True),
        ),
    ]
