# Generated by Django 5.0.6 on 2026-08-25 17:27

import django.db.models.deletion
import pld.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0010_amplia_estado_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='PldSolicitudEliminacionDoc',
            fields=[
                ('id_solicitud', models.CharField(default=pld.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('denominacion_doc', models.CharField(blank=True, max_length=250, null=True)),
                ('sociedad_rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('razon', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('solicitado_por', models.CharField(max_length=8)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_por', models.CharField(blank=True, max_length=8, null=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_resolucion', models.CharField(blank=True, max_length=500, null=True)),
                ('documento', models.ForeignKey(blank=True, db_column='id_kyc_doc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_eliminacion', to='pld.pldcontrapartedoc')),
            ],
            options={
                'db_table': 'pld_solicitudes_eliminacion_doc',
            },
        ),
    ]
