# Generated by Django 5.0.6 on 2026-08-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0011_solicitud_eliminacion_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='sociedad_nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
