# Generated by Django 5.0.6 on 2026-08-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0012_sociedad_nombre_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='proyecto',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pldsolicitudeliminaciondoc',
            name='proyecto',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
