# Generated by Django 5.0.6 on 2026-09-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0013_pldcontrapartekyc_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('fisica', 'Física'), ('moral', 'Moral'), ('fisica_act_emp', 'Física con actividad empresarial'), ('fideicomiso', 'Fideicomiso')], max_length=20, null=True),
        ),
    ]
