# Generated by Django 5.0.6 on 2026-09-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0014_pldcontrapartekyc_tipo_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pldcontrapartekyc',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('fisica', 'Física'), ('moral', 'Moral'), ('fideicomiso', 'Fideicomiso')], max_length=20, null=True),
        ),
    ]
