# Generated by Django 5.0.6 on 2026-09-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0015_alter_pldcontrapartekyc_tipo_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
