# Generated by Django 5.0.6 on 2026-09-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0016_pldcontrapartekyc_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
