# Generated by Django 5.0.6 on 2026-09-02 19:55

import django.db.models.deletion
import pld.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0017_pldcontrapartekyc_rfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PldRepresentanteLegal',
            fields=[
                ('id_representante', models.CharField(default=pld.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('REPRESENTANTE_LEGAL', 'Representante legal'), ('APODERADO', 'Apoderado')], default='REPRESENTANTE_LEGAL', max_length=20)),
                ('nombre_completo', models.CharField(max_length=250)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_identificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('autoridad_identificacion', models.CharField(blank=True, max_length=250, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc', models.ForeignKey(db_column='id_kyc', on_delete=django.db.models.deletion.CASCADE, related_name='representantes_legales', to='pld.pldcontrapartekyc')),
            ],
            options={
                'db_table': 'pld_representantes_legales',
            },
        ),
    ]
