# Generated by Django 5.0.6 on 2026-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0018_pldrepresentantelegal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldrepresentantelegal',
            name='es_beneficiario_controlador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pldrepresentantelegal',
            name='es_principal_del_tramite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pldrepresentantelegal',
            name='poder_facultades',
            field=models.CharField(blank=True, choices=[('PLEITOS_COBRANZAS', 'Pleitos y cobranzas'), ('ACTOS_ADMINISTRACION', 'Actos de administración'), ('ACTOS_DOMINIO', 'Actos de dominio'), ('PLEITOS_Y_ADMINISTRACION', 'Pleitos y cobranzas + Actos de administración'), ('OTRAS', 'Otras')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pldrepresentantelegal',
            name='poder_fecha_escritura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pldrepresentantelegal',
            name='poder_notario_nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pldrepresentantelegal',
            name='poder_notario_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pldrepresentantelegal',
            name='poder_numero_escritura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pldrepresentantelegal',
            name='poder_vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pldrepresentantelegal',
            name='porcentaje_participacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
