# Generated by Django 5.0.6 on 2026-09-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0019_pldrepresentantelegal_es_beneficiario_controlador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartedoc',
            name='obligatorio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartedoc',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CUESTIONARIO_RIESGO', 'Cuestionario de riesgo'), ('DECLARACION_ORIGEN_FONDOS', 'Declaración de origen de fondos'), ('EVIDENCIA_PEP', 'Evidencia de análisis PEP'), ('ORGANIGRAMA_ACCIONARIO', 'Organigrama accionario (KYB)'), ('OTRO', 'Otro (especificar en denominación)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartedoc',
            name='vigencia_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='categoria_cumplimiento',
            field=models.CharField(blank=True, choices=[('KYC', 'KYC — persona física'), ('KYB', 'KYB — persona moral'), ('PENDIENTE_REVISION', 'Pendiente de revisión manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='categoria_cumplimiento_manual',
            field=models.BooleanField(default=False),
        ),
    ]
