# Generated by Django 5.0.6 on 2026-09-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0022_alter_pldcontrapartedoc_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pldcontrapartedoc',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('IDENTIFICACION_OFICIAL', 'Identificación oficial'), ('ACTA_CONSTITUTIVA', 'Acta constitutiva'), ('CONSTANCIA_SITUACION_FISCAL', 'Constancia de Situación Fiscal'), ('INSCRIPCION_RPC', 'Inscripción en el Registro Público de Comercio'), ('INFO_BANCARIA', 'Carátula / información bancaria'), ('VALIDACION_TITULARIDAD_CUENTA', 'Validación de titularidad de la cuenta'), ('OPINION_CUMPLIMIENTO', 'Opinión de Cumplimiento (SAT)'), ('COMPROBANTE_DOMICILIO', 'Comprobante de domicilio'), ('CUESTIONARIO_RIESGO', 'Cuestionario de riesgo'), ('DECLARACION_ORIGEN_FONDOS', 'Declaración de origen de fondos'), ('EVIDENCIA_PEP', 'Evidencia de análisis PEP'), ('ORGANIGRAMA_ACCIONARIO', 'Organigrama accionario (KYB)')], max_length=35, null=True),
        ),
    ]
