# Generated by Django 5.0.6 on 2026-09-04 21:46

import django.db.models.deletion
import pld.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0023_pldcontrapartekyc_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PldDocumentoTicket',
            fields=[
                ('id_ticket', models.CharField(default=pld.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.CharField(blank=True, max_length=8, null=True)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.IntegerField(default=1)),
                ('uses_count', models.IntegerField(default=0)),
                ('first_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='pld.pldcontrapartedoc')),
            ],
            options={
                'db_table': 'pld_documento_tickets',
            },
        ),
    ]
