# Generated by Django 5.0.6 on 2026-10-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pld', '0025_alter_pldcontrapartedoc_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='es_pep',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='grado_riesgo',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('SIN_EVALUAR', 'Sin evaluar')], default='SIN_EVALUAR', max_length=20),
        ),
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='grado_riesgo_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pldcontrapartekyc',
            name='notas_riesgo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
