# Generated by Django 5.0.6 on 2026-08-19 16:46

import django.db.models.deletion
import materiales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManoObraCatalogo',
            fields=[
                ('id_mano_obra', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('etapa_constructiva', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=250)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'materiales_mano_obra_catalogo',
            },
        ),
        migrations.CreateModel(
            name='MaterialCatalogo',
            fields=[
                ('id_material', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('proveedor', models.CharField(blank=True, max_length=8, null=True)),
                ('cotizacion_fecha_vigencia', models.DateField(blank=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'materiales_catalogo',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=8)),
                ('denominacion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'materiales_presupuestos',
            },
        ),
        migrations.CreateModel(
            name='ConceptoPresupuesto',
            fields=[
                ('id_concepto', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('etapa_constructiva', models.CharField(max_length=150)),
                ('concepto', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=16)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('mano_obra', models.ForeignKey(blank=True, db_column='id_mano_obra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_presupuesto', to='materiales.manoobracatalogo')),
                ('material', models.ForeignKey(blank=True, db_column='id_material', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_presupuesto', to='materiales.materialcatalogo')),
                ('presupuesto', models.ForeignKey(db_column='id_presupuesto', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='materiales.presupuesto')),
            ],
            options={
                'db_table': 'materiales_conceptos_presupuesto',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoFirma',
            fields=[
                ('id_firma', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('firmante', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('presupuesto', models.ForeignKey(db_column='id_presupuesto', on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='materiales.presupuesto')),
            ],
            options={
                'db_table': 'materiales_presupuesto_firmas',
            },
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id_solicitud', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=8)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('solicitado_por', models.CharField(max_length=8)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='SOLICITADO', max_length=20)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='materiales.materialcatalogo')),
            ],
            options={
                'db_table': 'materiales_solicitudes',
            },
        ),
    ]
