# Generated by Django 5.0.6 on 2026-08-21 19:59

import django.db.models.deletion
import materiales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaRecepcion',
            fields=[
                ('id_evidencia', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('link_drive', models.CharField(blank=True, max_length=2083, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('registrado_por', models.CharField(max_length=8)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='materiales.solicitudmaterial')),
            ],
            options={
                'db_table': 'materiales_evidencias_recepcion',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
