# Generated by Django 5.0.6 on 2026-08-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_evidenciarecepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='SOLICITADO', max_length=20),
        ),
    ]
