# Generated by Django 5.0.6 on 2026-08-21 20:47

import django.db.models.deletion
import materiales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_alter_solicitudmaterial_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id_requisicion', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('folio', models.CharField(editable=False, max_length=40, unique=True)),
                ('proyecto', models.CharField(max_length=8)),
                ('etapa_constructiva', models.CharField(max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('num_viviendas', models.PositiveIntegerField(default=1)),
                ('presupuesto_asignado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de autorización'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('solicito_por', models.CharField(blank=True, max_length=8, null=True)),
                ('valido_por', models.CharField(blank=True, max_length=8, null=True)),
                ('autorizo_compra_por', models.CharField(blank=True, max_length=8, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('presupuesto', models.ForeignKey(db_column='id_presupuesto', on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones', to='materiales.presupuesto')),
            ],
            options={
                'db_table': 'materiales_requisiciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisicionLinea',
            fields=[
                ('id_linea', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('concepto_nombre', models.CharField(max_length=250)),
                ('cantidad_por_vivienda', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=16)),
                ('proveedor_cotizacion', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('concepto', models.ForeignKey(blank=True, db_column='id_concepto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_requisicion', to='materiales.conceptopresupuesto')),
                ('material', models.ForeignKey(blank=True, db_column='id_material', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_requisicion', to='materiales.materialcatalogo')),
                ('requisicion', models.ForeignKey(db_column='id_requisicion', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='materiales.requisicion')),
            ],
            options={
                'db_table': 'materiales_requisicion_lineas',
                'ordering': ['concepto_nombre'],
            },
        ),
    ]
