# Generated by Django 5.0.6 on 2026-09-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_requisicion_requisicionlinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='obra',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
