# Generated by Django 5.0.6 on 2026-09-18 16:56

import django.db.models.deletion
import materiales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_presupuesto_obra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicionlinea',
            options={'ordering': ['material_nombre']},
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='num_viviendas',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='presupuesto',
        ),
        migrations.RemoveField(
            model_name='requisicionlinea',
            name='cantidad_por_vivienda',
        ),
        migrations.RemoveField(
            model_name='requisicionlinea',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='requisicionlinea',
            name='concepto_nombre',
        ),
        migrations.AddField(
            model_name='requisicionlinea',
            name='material_nombre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisicionlinea',
            name='material',
            field=models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.PROTECT, related_name='lineas_requisicion', to='materiales.materialcatalogo'),
        ),
        migrations.CreateModel(
            name='RequisicionObra',
            fields=[
                ('id_requisicion_obra', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('obra', models.CharField(max_length=8)),
                ('requisicion', models.ForeignKey(db_column='id_requisicion', on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='materiales.requisicion')),
            ],
            options={
                'db_table': 'materiales_requisicion_obras',
                'unique_together': {('requisicion', 'obra')},
            },
        ),
    ]
