# Generated by Django 5.0.6 on 2026-09-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0006_alter_requisicionlinea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='id_solicitud_compra',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
    ]
