# Generated by Django 5.0.6 on 2026-09-22 17:55

import django.db.models.deletion
import materiales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_requisicion_id_solicitud_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoSuministro',
            fields=[
                ('id_contrato_suministro', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=8)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('link_documento', models.CharField(blank=True, max_length=2083, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'materiales_contratos_suministro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContratoSuministroLinea',
            fields=[
                ('id_linea', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('contrato', models.ForeignKey(db_column='id_contrato_suministro', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='materiales.contratosuministro')),
                ('material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.PROTECT, related_name='lineas_contrato_suministro', to='materiales.materialcatalogo')),
            ],
            options={
                'db_table': 'materiales_contrato_suministro_lineas',
                'unique_together': {('contrato', 'material')},
            },
        ),
    ]
