# Generated by Django 5.0.6 on 2026-09-22 19:05

import django.db.models.deletion
import materiales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0008_contratosuministro_contratosuministrolinea'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoSuministroProyecto',
            fields=[
                ('id_contrato_suministro_proyecto', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=8)),
                ('contrato', models.ForeignKey(db_column='id_contrato_suministro', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='materiales.contratosuministro')),
            ],
            options={
                'db_table': 'materiales_contrato_suministro_proyectos',
                'unique_together': {('contrato', 'proyecto')},
            },
        ),
    ]
