# Generated by Django 5.0.6 on 2026-09-22 19:47

import materiales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_contratosuministroproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialesNotificacion',
            fields=[
                ('id_notificacion', models.CharField(default=materiales.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('destinatario', models.CharField(max_length=8)),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'materiales_notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
