# Generated by Django 5.0.6 on 2026-09-03 15:50

import compras_tesoreria.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.CharField(default=compras_tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(blank=True, max_length=8, null=True)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_cotizacion', models.DateField(blank=True, null=True)),
                ('vigencia_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('link_drive', models.CharField(blank=True, max_length=2083, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_REVISION', 'Pendiente de revisión'), ('CONFIRMADA', 'Confirmada'), ('GANADORA', 'Ganadora'), ('DESCARTADA', 'Descartada')], default='PENDIENTE_REVISION', max_length=20)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'compras_cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id_solicitud', models.CharField(default=compras_tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=8)),
                ('requisicion', models.CharField(blank=True, max_length=8, null=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_COTIZACION', 'En cotización'), ('ORDEN_GENERADA', 'Orden generada'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('solicitado_por', models.CharField(blank=True, max_length=8, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'compras_solicitudes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionLinea',
            fields=[
                ('id_linea', models.CharField(default=compras_tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras_tesoreria.cotizacion')),
            ],
            options={
                'db_table': 'compras_cotizacion_lineas',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.CharField(default=compras_tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('folio', models.CharField(editable=False, max_length=40, unique=True)),
                ('proyecto', models.CharField(max_length=8)),
                ('proveedor', models.CharField(blank=True, max_length=8, null=True)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_orden', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al proveedor'), ('RECIBIDA_PARCIAL', 'Recibida parcial'), ('RECIBIDA_TOTAL', 'Recibida total'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('autorizado_por', models.CharField(blank=True, max_length=8, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='compras_tesoreria.cotizacion')),
                ('solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='compras_tesoreria.solicitudcompra')),
            ],
            options={
                'db_table': 'compras_ordenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraLinea',
            fields=[
                ('id_linea', models.CharField(default=compras_tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=16)),
                ('orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras_tesoreria.ordencompra')),
            ],
            options={
                'db_table': 'compras_orden_lineas',
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id_recepcion', models.CharField(default=compras_tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('recibido_por', models.CharField(blank=True, max_length=8, null=True)),
                ('link_drive', models.CharField(blank=True, max_length=2083, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras_tesoreria.ordencompra')),
            ],
            options={
                'db_table': 'compras_recepciones',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionLinea',
            fields=[
                ('id_linea', models.CharField(default=compras_tesoreria.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=14)),
                ('orden_linea', models.ForeignKey(db_column='id_orden_linea', on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras_tesoreria.ordencompralinea')),
                ('recepcion', models.ForeignKey(db_column='id_recepcion', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras_tesoreria.recepcion')),
            ],
            options={
                'db_table': 'compras_recepcion_lineas',
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='solicitud',
            field=models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='compras_tesoreria.solicitudcompra'),
        ),
    ]
