# Generated by Django 5.0.6 on 2026-09-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='proveedor_rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
