# Generated by Django 5.0.6 on 2026-09-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_tesoreria', '0002_cotizacion_proveedor_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al proveedor'), ('RECIBIDA_PARCIAL', 'Recibida parcial'), ('RECIBIDA_TOTAL', 'Recibida total'), ('CANCELADA', 'Cancelada'), ('CERRADA_CON_FALTANTE', 'Cerrada con faltante')], default='BORRADOR', max_length=20),
        ),
    ]
