# Generated by Django 5.0.6 on 2026-09-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_tesoreria', '0003_alter_ordencompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
