# Generated by Django 5.0.6 on 2026-09-22 19:09

from django.db import migrations, models


def backfill_vigencia_dias(apps, schema_editor):
    # 22/Sep/2026, "las cotizaciones duran una semana" - cotizaciones
    # existentes sin vigencia capturada por la IA se asumen 7 dias, mismo
    # default que las nuevas.
    Cotizacion = apps.get_model('compras_tesoreria', 'Cotizacion')
    Cotizacion.objects.filter(vigencia_dias__isnull=True).update(vigencia_dias=7)


class Migration(migrations.Migration):

    dependencies = [
        ('compras_tesoreria', '0004_ordencompra_iva_ordencompra_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='vigencia_dias',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
        migrations.RunPython(backfill_vigencia_dias, migrations.RunPython.noop),
    ]
