# Generated by Django 5.0.6 on 2026-09-23

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsSubproyecto',
            fields=[
                ('id_subproyecto', models.CharField(default=tickets.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('sociedad', models.CharField(max_length=13)),
                ('responsable', models.CharField(max_length=8)),
                ('estado', models.CharField(choices=[('PLANEADO', 'Planeado'), ('EN CURSO', 'En curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PLANEADO', max_length=20)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('progreso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subproyectos', to='tickets.ticketsproyecto')),
            ],
            options={
                'db_table': 'tickets_subproyectos',
            },
        ),
    ]
