# Generated by Django 5.0.6 on 2026-09-24 14:50

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketssubproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.CharField(default=tickets.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN CURSO', 'En curso'), ('EN REVISION', 'En revisión'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('asignado_a', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha_inicio_prog', models.DateField(blank=True, null=True)),
                ('fecha_fin_prog', models.DateField(blank=True, null=True)),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estimacion_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carpeta', models.CharField(blank=True, max_length=2083, null=True)),
                ('instrucciones_entrega', models.CharField(blank=True, max_length=1000, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('id_subproyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketssubproyecto')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
