# Generated by Django 5.0.6 on 2026-09-24 14:53

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsDependencia',
            fields=[
                ('id_dependencia', models.CharField(default=tickets.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FIN_A_INICIO', 'Fin a inicio'), ('INICIO_A_INICIO', 'Inicio a inicio'), ('FIN_A_FIN', 'Fin a fin'), ('INICIO_A_FIN', 'Inicio a fin')], default='FIN_A_INICIO', max_length=20)),
                ('ventaja_desfase_dias', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=8)),
                ('predecesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_como_predecesora', to='tickets.ticket')),
                ('sucesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_como_sucesora', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets_dependencias',
            },
        ),
        migrations.CreateModel(
            name='TicketsLog',
            fields=[
                ('id_log', models.CharField(default=tickets.models._short_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('progreso_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('horas_incurridas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('evidencia', models.CharField(blank=True, max_length=2083, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=8)),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets_log',
            },
        ),
        migrations.AddConstraint(
            model_name='ticketsdependencia',
            constraint=models.UniqueConstraint(fields=('predecesora', 'sucesora'), name='unica_dependencia_predecesora_sucesora'),
        ),
        migrations.AddConstraint(
            model_name='ticketsdependencia',
            constraint=models.CheckConstraint(check=models.Q(('predecesora', models.F('sucesora')), _negated=True), name='dependencia_no_autoreferencia'),
        ),
    ]
