# Generated by Django 5.0.6 on 2026-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketsdependencia_ticketslog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketslog',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='ticketslog',
            name='evidencia',
        ),
        migrations.AddField(
            model_name='ticketslog',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticketslog',
            name='descripcion_archivo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ticketslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketslog',
            name='updated_by',
            field=models.CharField(default='sistema', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketslog',
            name='url_archivo',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsdependencia',
            name='tipo',
            field=models.CharField(choices=[('ESTRICTO', 'Estricto'), ('FLEXIBLE', 'Flexible')], default='ESTRICTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketslog',
            name='accion',
            field=models.CharField(choices=[('COMENTARIO', 'Comentario'), ('ACTUALIZACION', 'Actualización'), ('CARGA ARCHIVO', 'Carga de archivo'), ('CAMBIO ASIGNACION', 'Cambio de asignación'), ('OTRO', 'Otro')], default='ACTUALIZACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketslog',
            name='horas_incurridas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
