// Catalogo estatico de paises/gentilicios y estados de Mexico (25/Ago/2026,
// requerimiento real del cliente: dropdowns en vez de texto libre para
// pais/nacionalidad/estado en el formulario publico de PLD, ver
// app/pld-ticket/[token]/page.tsx). Estatico a proposito - se evaluo
// REST Countries pero la version gratuita sin llave esta deprecada (la
// nueva exige API key/registro); un catalogo fijo es mas ligero (sin red,
// sin key, sin limite de rate) para un dato que casi no cambia.
export interface PaisOption {
  pais: string;
  gentilicio: string;
}

export const PAISES: PaisOption[] = [
  { pais: "México", gentilicio: "Mexicana" },
  { pais: "Estados Unidos", gentilicio: "Estadounidense" },
  { pais: "Canadá", gentilicio: "Canadiense" },
  { pais: "Guatemala", gentilicio: "Guatemalteca" },
  { pais: "Belice", gentilicio: "Beliceña" },
  { pais: "Honduras", gentilicio: "Hondureña" },
  { pais: "El Salvador", gentilicio: "Salvadoreña" },
  { pais: "Nicaragua", gentilicio: "Nicaragüense" },
  { pais: "Costa Rica", gentilicio: "Costarricense" },
  { pais: "Panamá", gentilicio: "Panameña" },
  { pais: "Cuba", gentilicio: "Cubana" },
  { pais: "República Dominicana", gentilicio: "Dominicana" },
  { pais: "Haití", gentilicio: "Haitiana" },
  { pais: "Jamaica", gentilicio: "Jamaiquina" },
  { pais: "Colombia", gentilicio: "Colombiana" },
  { pais: "Venezuela", gentilicio: "Venezolana" },
  { pais: "Ecuador", gentilicio: "Ecuatoriana" },
  { pais: "Perú", gentilicio: "Peruana" },
  { pais: "Bolivia", gentilicio: "Boliviana" },
  { pais: "Chile", gentilicio: "Chilena" },
  { pais: "Argentina", gentilicio: "Argentina" },
  { pais: "Uruguay", gentilicio: "Uruguaya" },
  { pais: "Paraguay", gentilicio: "Paraguaya" },
  { pais: "Brasil", gentilicio: "Brasileña" },
  { pais: "Guyana", gentilicio: "Guyanesa" },
  { pais: "Surinam", gentilicio: "Surinamesa" },
  { pais: "España", gentilicio: "Española" },
  { pais: "Portugal", gentilicio: "Portuguesa" },
  { pais: "Francia", gentilicio: "Francesa" },
  { pais: "Reino Unido", gentilicio: "Británica" },
  { pais: "Irlanda", gentilicio: "Irlandesa" },
  { pais: "Alemania", gentilicio: "Alemana" },
  { pais: "Países Bajos", gentilicio: "Neerlandesa" },
  { pais: "Bélgica", gentilicio: "Belga" },
  { pais: "Luxemburgo", gentilicio: "Luxemburguesa" },
  { pais: "Suiza", gentilicio: "Suiza" },
  { pais: "Austria", gentilicio: "Austriaca" },
  { pais: "Italia", gentilicio: "Italiana" },
  { pais: "Vaticano", gentilicio: "Vaticana" },
  { pais: "San Marino", gentilicio: "Sanmarinense" },
  { pais: "Andorra", gentilicio: "Andorrana" },
  { pais: "Mónaco", gentilicio: "Monegasca" },
  { pais: "Grecia", gentilicio: "Griega" },
  { pais: "Chipre", gentilicio: "Chipriota" },
  { pais: "Malta", gentilicio: "Maltesa" },
  { pais: "Dinamarca", gentilicio: "Danesa" },
  { pais: "Noruega", gentilicio: "Noruega" },
  { pais: "Suecia", gentilicio: "Sueca" },
  { pais: "Finlandia", gentilicio: "Finlandesa" },
  { pais: "Islandia", gentilicio: "Islandesa" },
  { pais: "Polonia", gentilicio: "Polaca" },
  { pais: "República Checa", gentilicio: "Checa" },
  { pais: "Eslovaquia", gentilicio: "Eslovaca" },
  { pais: "Hungría", gentilicio: "Húngara" },
  { pais: "Eslovenia", gentilicio: "Eslovena" },
  { pais: "Croacia", gentilicio: "Croata" },
  { pais: "Bosnia y Herzegovina", gentilicio: "Bosnia" },
  { pais: "Serbia", gentilicio: "Serbia" },
  { pais: "Montenegro", gentilicio: "Montenegrina" },
  { pais: "Macedonia del Norte", gentilicio: "Macedonia" },
  { pais: "Albania", gentilicio: "Albanesa" },
  { pais: "Rumania", gentilicio: "Rumana" },
  { pais: "Bulgaria", gentilicio: "Búlgara" },
  { pais: "Moldavia", gentilicio: "Moldava" },
  { pais: "Ucrania", gentilicio: "Ucraniana" },
  { pais: "Bielorrusia", gentilicio: "Bielorrusa" },
  { pais: "Rusia", gentilicio: "Rusa" },
  { pais: "Estonia", gentilicio: "Estonia" },
  { pais: "Letonia", gentilicio: "Letona" },
  { pais: "Lituania", gentilicio: "Lituana" },
  { pais: "Turquía", gentilicio: "Turca" },
  { pais: "Israel", gentilicio: "Israelí" },
  { pais: "Palestina", gentilicio: "Palestina" },
  { pais: "Líbano", gentilicio: "Libanesa" },
  { pais: "Jordania", gentilicio: "Jordana" },
  { pais: "Siria", gentilicio: "Siria" },
  { pais: "Irak", gentilicio: "Iraquí" },
  { pais: "Irán", gentilicio: "Iraní" },
  { pais: "Arabia Saudita", gentilicio: "Saudí" },
  { pais: "Emiratos Árabes Unidos", gentilicio: "Emiratí" },
  { pais: "Qatar", gentilicio: "Catarí" },
  { pais: "Kuwait", gentilicio: "Kuwaití" },
  { pais: "Baréin", gentilicio: "Bareiní" },
  { pais: "Omán", gentilicio: "Omaní" },
  { pais: "Yemen", gentilicio: "Yemení" },
  { pais: "Egipto", gentilicio: "Egipcia" },
  { pais: "Marruecos", gentilicio: "Marroquí" },
  { pais: "Argelia", gentilicio: "Argelina" },
  { pais: "Túnez", gentilicio: "Tunecina" },
  { pais: "Libia", gentilicio: "Libia" },
  { pais: "Sudáfrica", gentilicio: "Sudafricana" },
  { pais: "Nigeria", gentilicio: "Nigeriana" },
  { pais: "Kenia", gentilicio: "Keniana" },
  { pais: "Etiopía", gentilicio: "Etíope" },
  { pais: "Ghana", gentilicio: "Ghanesa" },
  { pais: "Senegal", gentilicio: "Senegalesa" },
  { pais: "China", gentilicio: "China" },
  { pais: "Japón", gentilicio: "Japonesa" },
  { pais: "Corea del Sur", gentilicio: "Surcoreana" },
  { pais: "Corea del Norte", gentilicio: "Norcoreana" },
  { pais: "India", gentilicio: "India" },
  { pais: "Pakistán", gentilicio: "Pakistaní" },
  { pais: "Bangladés", gentilicio: "Bangladesí" },
  { pais: "Sri Lanka", gentilicio: "Esrilanquesa" },
  { pais: "Nepal", gentilicio: "Nepalí" },
  { pais: "Afganistán", gentilicio: "Afgana" },
  { pais: "Kazajistán", gentilicio: "Kazaja" },
  { pais: "Uzbekistán", gentilicio: "Uzbeka" },
  { pais: "Mongolia", gentilicio: "Mongola" },
  { pais: "Vietnam", gentilicio: "Vietnamita" },
  { pais: "Tailandia", gentilicio: "Tailandesa" },
  { pais: "Filipinas", gentilicio: "Filipina" },
  { pais: "Malasia", gentilicio: "Malasia" },
  { pais: "Singapur", gentilicio: "Singapurense" },
  { pais: "Indonesia", gentilicio: "Indonesia" },
  { pais: "Camboya", gentilicio: "Camboyana" },
  { pais: "Laos", gentilicio: "Laosiana" },
  { pais: "Myanmar", gentilicio: "Birmana" },
  { pais: "Taiwán", gentilicio: "Taiwanesa" },
  { pais: "Hong Kong", gentilicio: "Hongkonesa" },
  { pais: "Australia", gentilicio: "Australiana" },
  { pais: "Nueva Zelanda", gentilicio: "Neozelandesa" },
];

// Estados de Mexico (25/Ago/2026, requerimiento real del cliente: dropdown
// fijo en vez de texto libre). Municipio/colonia se quedan como texto
// libre a proposito - ningun dataset global (incluido REST Countries)
// llega a ese nivel de detalle, solo SEPOMEX/Copomex (con costo/API key),
// decision pendiente de evaluar aparte si algun dia se requiere.
export const ESTADOS_MEXICO = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Coahuila",
  "Colima",
  "Durango",
  "Estado de México",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
];

// Tipos de identificacion oficial aceptados para KYC (25/Ago/2026) -
// mismo campo que ya existia como texto libre (tipo_identificacion),
// ahora acotado a un catalogo cerrado.
export const TIPOS_IDENTIFICACION = [
  "INE / IFE",
  "Pasaporte",
  "Cédula profesional",
  "Forma migratoria (FM2/FM3)",
  "Cartilla del Servicio Militar Nacional",
  "Licencia de conducir",
];
